[project]
name = "cdot-wzdx-translator"
import-names=["wzdx"]
version = "1.4.4-rc1"
description = "CDOT Work Zone WZDx Translators"
authors = [
    {name = "CDOT",email = "CDOT_rtdh_prod@state.co.us"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "xmltodict (>=1.0.2,<2.0.0)",
    "jsonschema (>=4.25.1,<5.0.0)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "shapely (>=2.1.2,<3.0.0)",
    "geopy (>=2.4.1,<3.0.0)",
    "numpy (>=2.3.4,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "pytz (>=2025.2,<2026.0)",
    "regex (>=2025.11.3,<2026.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "time-machine (>=2.19.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
